resource "oci_core_drg_attachment_management" "this" {
  attachment_type    = var.attachment_type
  compartment_id     = var.compartment_ocid
  network_id         = var.network_id
  drg_id             = var.drg_id
  display_name       = var.display_name
  drg_route_table_id = var.drg_route_table_id
}

# DRG  Attachments  for  virtual  circuits, IPSec  tunnels,  and  remote
# peering connections  are created  (and deleted) automatically  on your
# behalf when  you create  (or delete) the  network object.  Hence, this
# management resource is used to update these types of autogenerated DRG
# Attachments.  The user cannot create DRG attachments of these types as
# needed.
